baseURL = 'https://oribarilan.github.io/'
languageCode = 'en-us'
title = 'Ori Bar-ilan'
theme = "nightfall"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
pagerSize = 10

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"
  [[menu.header]]
    name = "whoami"
    weight = 1
    url = "/about"

[params]
user = "oribarilan"
hostname = "github.io"
footerHtml = ""

# Color theme: default, tokyonight, gruvbox, catppuccin, nord
colorTheme = "default"

openLinksInNewTab = true
displayDateFormat = "2006-01-02"

# Global metadata display settings
showMetadata = true
showPublishedDate = true
showReadingTime = true
showTags = true
showAuthors = false
showCategories = true

  [params.author]
    name = "Ori Bar-ilan"
    email = "your-email@example.com"
    avatar = "ori.png"
    avatarSize = "size-l"
    description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

# Add your social links here
# [[params.social]]
# key = 0
# name = "github"
# url = "https://github.com/oribarilan"
# target = "_blank"
# aria = "GitHub Profile"
